### ISSUE TITLE
Загрузка и Разгрузка перепутаны местами

### ISSUE THREAD

**Issue by Oleg-Avdeev** [Falcon-RawByte/Web_CIS_Development#1]
Срочно поправить! Безобразие, **неопрядок**!
# Срочно поправить! Безобразие, неопрядок!

**Comment by HeavyOranJS** [comment]
Tête Cher, la mise en page html est votre responsabilité, s'il vous plaît corriger vous-même. Merci beaucoup, il est un plaisir de travailler avec vous.
_ORANGES lourds_

**Comment by Oleg-Avdeev** [comment]
Oui, oui, pardon, monsieur pomeranets.

**Comment by HeavyOranJS** [comment]
Thx1 u r the best bozz in the world

Sincerely yours, 
monsieur pomeranets.
