### ISSUE TITLE
Баг скрипта обработки количества записей

### ISSUE THREAD

**Issue by Oleg-Avdeev** [Falcon-RawByte/Web_CIS_Development#10]
Речь идёт про элемент <input type="number" class="quantity" id = "load_inner" size="2" maxlength="2" max="15" min = "1" value="1"> и аналогичный для разгрузки.
Чтобы правильно работал инпут с числами нужно снимать фокус с элемента каждый раз перед нажатием. Если несколько раз нажать на стрелочку, не снимая фокус, то не вызывается скрипт обработки изменения значения.

**Comment by Oleg-Avdeev** [comment]
input type="number" class="quantity" id = "load_inner" size="2" maxlength="2" max="15" min = "1" value="1"
Вот этот инпут

**Comment by Oleg-Avdeev** [comment]
http://stackoverflow.com/questions/17317465/jquery-textbox-change-event-doesnt-fire-until-textbox-loses-focus

**Comment by HeavyOranJS** [comment]
what da hell
