### ISSUE TITLE
Анимация исчезновения блоков

### ISSUE THREAD

**Issue by Oleg-Avdeev** [Falcon-RawByte/Web_CIS_Development#2]
В JQuery можно параллельно с FadeOut/In анимировать высоту блока. Попробовать найти параметры CSS, чтобы наполнение блока не задавало высоту и обрезалось краями.

Исправить анимацию .block

**Comment by HeavyOranJS** [comment]
Анимирование высоты выполнено
Анимацию появления когда-нибудь возможно исправлю, потому что хочется но блин
